---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "DNSWatch"
subtitle: "Links"
logo: "favicon.ico"
icon: "internet-explorer"
header: false
footer: false
columns: "2"
theme: sui
colors:
  light:
    background: white
    highlight-primary: transparent
    highlight-secondary: transparent
    highlight-hover: "#4a4a4a"
    text-title: "#424242"
    text: "#424242"
  dark:
    background: white
    highlight-primary: transparent
    highlight-secondary: transparent
    highlight-hover: "#200b35"
    text-title: "#424242"
    text: "#424242"

stylesheet:
  - "assets/custom.css"
# message:
#   style: "is-dark"
#   title: "Pro Tip － Set this as the \"new tab\" page for your browser."
#   content: ""

# Optional navbar
links:
  - name: "DNSWatch Explorer"
    icon: "fab fa-internet-explorer"
    url: "#"

# Services
services:
  - name: "Code"
    items:
      - name: "Current Sprint"
        url: "https://jira.watchguard.com/secure/RapidBoard.jspa?projectKey=DNSW&rapidView=525"
        logo: "assets/tools/sprint.svg"
        target: "_blank"
      - name: "Approved PRs"
        url: "https://github.com/percipient/strongarm/pulls?q=is%3Apr+is%3Aopen+review%3Aapproved"
        logo: "assets/tools/pr.svg"
        target: "_blank"
      - name: "Github Issues"
        url: "https://github.com/percipient/strongarm/issues"
        logo: "assets/tools/issue.svg"
        target: "_blank"
      - name: "Jira Issues"
        url: "https://jira.watchguard.com/projects/DNSW/issues/DNSW-127?filter=allopenissues"
        logo: "assets/tools/jira.svg"
        target: "_blank"
      - name: "CircleCI"
        # subtitle: "app.circleci.com/pipelines/github/percipient"
        url: "https://app.circleci.com/pipelines/github/percipient/strongarm"
        logo: "assets/tools/circle.svg"
        target: "_blank"
      - name: "Travis"
        # subtitle: "travis-ci.com/github/percipient/strongarm"
        url: "//travis-ci.com/github/percipient/strongarm"
        logo: "assets/tools/travis.svg"
        target: "_blank"
  - name: "Monitoring"
    items:
      - name: "Sentry"
        logo: "assets/tools/sentry.svg"
        # subtitle: "sentry.io/organizations/dnswatch/issues"
        url: "https://sentry.io/organizations/dnswatch/issues"
        target: "_blank"
      - name: "PaperTrail"
        logo: "assets/tools/papertrail.svg"
        url: "https://my.papertrailapp.com/events"
        target: "_blank"
      - name: "RabbitMQ"
        # subtitle: "customer.cloudamqp.com/instance/23645/sso?goto=details/mgmt"
        url: "//customer.cloudamqp.com/instance/23645/sso?goto=details/mgmt"
        logo: "assets/tools/rabbitmq.svg"
        target: "_blank"
      - name: "CloudAMQP"
        # subtitle: "customer.cloudamqp.com/instance"
        url: "//customer.cloudamqp.com/instance"
        logo: "assets/tools/cloudamqp.svg"
        target: "_blank"
      - name: "Mongo"
        # subtitle: "cloud.mongodb.com/v2"
        url: "//cloud.mongodb.com/v2"
        logo: "assets/tools/mongo.svg"
        target: "_blank"
      - name: "Datadog"
        # subtitle: "app.datadoghq.com/dashboard/lists"
        url: "//app.datadoghq.com/dashboard/lists"
        logo: "assets/tools/datadog.svg"
        target: "_blank"
      - name: "PagerDuty"
        logo: "assets/tools/pagerduty.png"
        # subtitle: "percipient.pagerduty.com/incidents"
        url: "https://percipient.pagerduty.com/incidents"
        target: "_blank"
      - name: "Pingdom"
        # subtitle: "my.pingdom.com/app"
        url: "//my.pingdom.com/app"
        logo: "assets/tools/pingdom.svg"
        target: "_blank"
  - name: "Communication"
    items:
      - name: "StatusPage"
        # subtitle: "manage.statuspage.io"
        url: "//manage.statuspage.io"
        logo: "assets/tools/statuspage.svg"
        target: "_blank"
      - name: "Teams"
        # subtitle: "percipientnetworks.slack.com"
        url: "msteams:/l/chat/"
        logo: "assets/tools/teams.svg"
        target: "_blank"
      - name: "Slack"
        # subtitle: "percipientnetworks.slack.com"
        url: "//percipientnetworks.slack.com"
        logo: "assets/tools/slack.svg"
        target: "_blank"
      - name: "Groove"
        # subtitle: "strongarm.groovehq.com"
        url: "//strongarm.groovehq.com"
        logo: "assets/tools/groove.svg"
        target: "_blank"
      - name: "AuthPoint Portal"
        logo: "assets/tools/authpoint.png"
        url: "https://usa.authpoint.watchguard.com/watchguard/resources"
        target: "_blank"
      - name: "Confluence"
        logo: "assets/tools/confluence.svg"
        url: "https://confluence.watchguard.com/display/DNSW"
        target: "_blank"
  - name: "AWS"
    items:
      - name: "EC2"
        # subtitle: "us-west-1.console.aws.amazon.com/ec2"
        url: "//us-west-1.console.aws.amazon.com/ec2"
        logo: "assets/tools/ec2.svg"
        target: "_blank"
      - name: "CodeDeploy"
        # subtitle: "us-west-1.console.aws.amazon.com/ec2"
        url: "//console.aws.amazon.com/codesuite/codedeploy/deployments"
        logo: "assets/tools/codedeploy.svg"
        target: "_blank"
      - name: "RDS"
        # subtitle: "us-west-1.console.aws.amazon.com/ec2"
        url: "https://console.aws.amazon.com/rds/home"
        logo: "assets/tools/rds.svg"
        target: "_blank"
      - name: "CloudFormation"
        # subtitle: "us-west-1.console.aws.amazon.com/ec2"
        url: "https://console.aws.amazon.com/cloudformation/home"
        logo: "assets/tools/cfn.svg"
        target: "_blank"

# Authpoint
#   Jira
#   Confluence
